{
    'name': 'Hospital Management System',
    'version': '1.0',
    'summary': 'Simple HMS module for managing patients',
    'sequence': -100,
    'description': """Hospital Management System""",
    'category': 'Productivity',
    'author': 'Your Name',
    'depends': ['base', 'contacts'],
    'data': [
        'security/hms_groups.xml',
        'security/ir.model.access.csv',
        'views/dashboard_views.xml',
        'views/patient_views.xml',
        'views/department_views.xml',
        'views/doctors_views.xml',
        'views/partner_views.xml',
        'report/patient_report.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}